#docker compose to start the app and mysql
version: "3.9"
services:
  app:
    image: myhp:latest
    ports:
      - "8000:8000" # map container port 80 to host port 8080
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'sql_app'
      MYSQL_USER: 'ces'
      MYSQL_PASSWORD: 'Quizz2012'
      MYSQL_ROOT_PASSWORD: 'Quizz2012'
    ports:
      - "3306:3306"
    volumes: [mysql:/var/lib/mysql]

volumes:
  mysql: